"""
Demo 01 - RAG vs Graph-RAG with LangGraph
==========================================

KEY CONCEPT: Compare two retrieval strategies (traditional RAG vs Graph-RAG)
to show how structured knowledge (graphs) reduces hallucinations.

LANGGRAPH ARCHITECTURE:
    - We use a StateGraph with typed state (TypedDict)
    - Each agent is an independent graph with its own tool-calling loop
    - The "reactive loop" is: LLM decides -> has tool_calls? -> execute tools -> back to LLM

WHAT YOU'LL LEARN:
    1. How to define state with TypedDict and reducers (Annotated)
    2. How to create tools with @tool from LangChain
    3. How to use bind_tools() so the LLM knows which tools it has
    4. How to build the basic agentic pattern: llm_node -> conditional_edge -> tool_node -> loop
    5. How to compile and run a graph
"""
import os

os.environ["OTEL_SDK_DISABLED"] = "true"

from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# LANGGRAPH AND LANGCHAIN IMPORTS
# ---------------------------------------------------------------------------
# langgraph: the graph framework for agents
# langchain_openai: the connector for OpenAI models
# langchain_core: base types (messages, tools)
from langgraph.graph import StateGraph, MessagesState, START, END
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import SystemMessage, HumanMessage, ToolMessage

from typing import Literal

# Dependencies for RAG and Graph-RAG
from neo4j import GraphDatabase
import faiss
import json
from sentence_transformers import SentenceTransformer

# ---------------------------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------------------------
NEO4J_URI = os.getenv("NEO4J_URI", "neo4j://127.0.0.1:7687")
NEO4J_USER = os.getenv("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "password")

# ---------------------------------------------------------------------------
# EMBEDDING MODEL (for vector RAG)
# ---------------------------------------------------------------------------
# SentenceTransformer converts text into 384-dimensional numeric vectors.
# Two similar texts will have nearby vectors in the embedding space.
embed_model = SentenceTransformer("all-MiniLM-L6-v2")

# Load pre-built FAISS index and documents
# (these files are generated by build_graph.py from the original demo)
index = faiss.read_index("faqs_vector.index")
with open("faqs_docs.json", "r", encoding="utf-8") as f:
    documents = json.load(f)

# ---------------------------------------------------------------------------
# TOOL DEFINITIONS
# ---------------------------------------------------------------------------
# In LangGraph, tools are defined with @tool from langchain_core.
# Very similar to Strands: a decorated function with a descriptive docstring.
#
# KEY DIFFERENCE from Strands:
#   Strands:   from strands import tool     -> @tool
#   LangGraph: from langchain_core.tools import tool -> @tool
#
# The docstring is CRITICAL: the LLM uses it to decide when to call the tool.


@tool
def search_faqs(query: str) -> str:
    """Search hotel FAQs using vector similarity (Traditional RAG).

    Use this to find relevant FAQ information about hotels.
    Returns the top 3 most similar documents to the query.
    """
    query_embedding = embed_model.encode([query])
    distances, indices = index.search(query_embedding.astype("float32"), 3)

    results = []
    for idx in indices[0]:
        doc = documents[idx]
        results.append(f"[{doc['filename']}]\n{doc['text'][:500]}...")

    return "\n\n".join(results)


@tool
def query_knowledge_graph(cypher_query: str) -> str:
    """Execute a Cypher query against the hotel knowledge graph.

    Cypher is Neo4j's query language for graph databases. It uses pattern matching
    to query relationships between entities. Think of it like SQL for graphs.

    Example: MATCH (h:Hotel)-[:HAS_ROOM]->(r:Room) WHERE h.name = 'Marriott' RETURN r.price

    Node labels: Hotel, Room, Amenity, Policy, Service

    Hotel properties: name, address, guestRating, totalRooms, email, phone
    Room properties: name (e.g. "Standard Room"), price, maxOccupancy
    Amenity properties: name (e.g. "Outdoor Swimming Pool", "WiFi")
    Policy properties: name (e.g. "Check-in Policy"), details

    Relationships:
    - (Hotel)-[:HAS_ROOM]->(Room)
    - (Hotel)-[:OFFERS_AMENITY]->(Amenity)
    - (Hotel)-[:HAS_POLICY]->(Policy)
    - (Hotel)-[:PROVIDES_SERVICE]->(Service)

    Location is in Hotel.address property (e.g. "789 Corniche el-Nil, Cairo 11519").
    To find hotels by location, use: WHERE h.address CONTAINS 'Cairo'
    """
    driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))

    with driver.session() as session:
        try:
            result = session.run(cypher_query)
            records = list(result)

            if not records:
                return "No results found."

            output = f"Found {len(records)} results:\n"
            for record in records[:15]:
                row = {k: v for k, v in record.items()}
                output += f"  {row}\n"

            return output
        except Exception as e:
            return f"Query error: {str(e)}"
        finally:
            driver.close()


# ---------------------------------------------------------------------------
# LLM MODEL
# ---------------------------------------------------------------------------
# ChatOpenAI is LangChain's wrapper for the OpenAI API.
# temperature=0 for deterministic responses (less creativity, more precision).
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

# ---------------------------------------------------------------------------
# FUNCTION: Create an agent with tools (reusable pattern)
# ---------------------------------------------------------------------------
# This function encapsulates the most common LangGraph pattern:
#   START -> llm_node -> (has tool_calls?) -> tool_node -> llm_node -> ... -> END
#
# CONCEPT: MessagesState
#   A TypedDict with a single field: messages (list of messages).
#   Uses a "reducer" that ACCUMULATES messages (append), not replace.
#   This keeps the entire conversation in the state.


def create_tool_agent(agent_tools: list, system_prompt: str):
    """
    Create a LangGraph graph with the basic agentic pattern.

    STEP BY STEP:
    1. bind_tools() - Tells the LLM which tools it can use
    2. llm_node - Invokes the LLM with messages + system prompt
    3. tool_node - Executes the tools the LLM requested
    4. should_continue - Decides whether to keep looping or finish
    5. compile() - Converts the graph definition into a runnable

    DIAGRAM:
        START -> llm_node --[has tools?]--> tool_node -> llm_node
                           \--[no tools]---> END
    """
    # STEP 1: bind_tools
    # "Binds" the tools to the model. Internally, this adds each tool's
    # definition (name, description, parameters) to the API call payload.
    # This way the LLM knows it can call these tools.
    model_with_tools = llm.bind_tools(agent_tools)

    # Dictionary for quick tool lookup by name
    tools_by_name = {t.name: t for t in agent_tools}

    # STEP 2: LLM Node
    # Receives the state (with accumulated messages), prepends the system prompt,
    # and calls the LLM. The result is an AIMessage that may contain:
    #   - Only text (final response)
    #   - tool_calls (the LLM wants to use a tool)
    def llm_node(state: MessagesState):
        messages = [SystemMessage(content=system_prompt)] + state["messages"]
        response = model_with_tools.invoke(messages)
        # Return {"messages": [response]} -> the reducer APPENDS it to state
        return {"messages": [response]}

    # STEP 3: Tool execution node
    # Reads tool_calls from the last message (AIMessage), executes each tool,
    # and returns results as ToolMessages.
    # IMPORTANT: Each ToolMessage must have the correct tool_call_id
    # so the LLM knows which tool_call each result corresponds to.
    def tool_node(state: MessagesState):
        results = []
        for tc in state["messages"][-1].tool_calls:
            tool_fn = tools_by_name[tc["name"]]
            observation = tool_fn.invoke(tc["args"])
            results.append(
                ToolMessage(content=str(observation), tool_call_id=tc["id"])
            )
        return {"messages": results}

    # STEP 4: Conditional routing function
    # If the last message has tool_calls -> go to tool_node
    # If not -> go to END (the agent is done)
    def should_continue(state: MessagesState) -> Literal["tool_node", "__end__"]:
        last_message = state["messages"][-1]
        if last_message.tool_calls:
            return "tool_node"
        return "__end__"

    # STEP 5: Build the graph
    # StateGraph: manages typed state through the graph
    graph = StateGraph(MessagesState)

    # Add nodes (each node is a function that receives and returns state)
    graph.add_node("llm_node", llm_node)
    graph.add_node("tool_node", tool_node)

    # Add edges (connections between nodes)
    graph.add_edge(START, "llm_node")  # START always goes to LLM first
    graph.add_conditional_edges(
        "llm_node",  # From this node...
        should_continue,  # Use this function to decide...
        ["tool_node", END],  # The possible destinations
    )
    graph.add_edge("tool_node", "llm_node")  # After executing tools, back to LLM

    # compile() converts the graph definition into a runnable object
    return graph.compile()


# ---------------------------------------------------------------------------
# CREATE BOTH AGENTS
# ---------------------------------------------------------------------------
# RAG AGENT: Only has the vector search tool (FAISS)
rag_agent = create_tool_agent(
    agent_tools=[search_faqs],
    system_prompt="You are a travel agent. Use vector search to find relevant FAQ information.",
)

# GRAPH-RAG AGENT: Only has the Cypher query tool (Neo4j)
graph_agent = create_tool_agent(
    agent_tools=[query_knowledge_graph],
    system_prompt="You are a travel agent. Use the knowledge base to answer questions accurately. You can run multiple queries to explore the data.",
)

# ---------------------------------------------------------------------------
# RUN THE COMPARISON
# ---------------------------------------------------------------------------
print("=" * 70)
print("TRAVEL AGENT COMPARISON: Traditional RAG vs Graph-RAG (LangGraph)")
print("=" * 70)

queries = [
    # Test 1: Aggregation - RAG cannot compute, Graph-RAG can (uses AVG in Cypher)
    "What is the average guest rating across all hotels in Paris?",
    # Test 2: Precise counting - RAG guesses, Graph-RAG counts (uses COUNT)
    "How many hotels have a swimming pool as an amenity?",
    # Test 3: Multi-hop reasoning - RAG limited to top-k, Graph-RAG traverses the graph
    "What are the room types and prices for the highest rated hotel?",
    # Test 4: Out-of-domain - RAG may hallucinate, Graph-RAG says "no data"
    "Tell me about hotels in Antarctica",
]

for query in queries:
    print(f"\n{'='*70}")
    print(f"Query: {query}")
    print("=" * 70)

    # Traditional RAG
    print("\n[TRADITIONAL RAG - Vector Search]")
    print("-" * 70)
    # invoke() runs the full graph until it reaches END
    # We pass the user message as a HumanMessage
    result = rag_agent.invoke({"messages": [HumanMessage(content=query)]})
    # The last message in state["messages"] is the LLM's final response
    print(result["messages"][-1].content[:300] + "...")

    # Graph-RAG
    print("\n[GRAPH-RAG - Knowledge Graph]")
    print("-" * 70)
    result = graph_agent.invoke({"messages": [HumanMessage(content=query)]})
    print(result["messages"][-1].content[:300] + "...")

print("\n" + "=" * 70)
print("KEY INSIGHTS")
print("=" * 70)
print(
    """
Traditional RAG: Semantic similarity, may miss context or hallucinate
Graph-RAG: Structured queries on extracted entities, precise answers
Result: Graph-RAG eliminates hallucinations with verified data
"""
)
